package com.app.services;

import java.time.Year;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.app.dtos.response.BookingResponseDTO;
import com.app.entities.Attendee;
import com.app.entities.Booking;
import com.app.entities.TicketType;
import com.app.enums.BookingStatus;
import com.app.repositories.AttendeeRepository;
import com.app.repositories.BookingRepository;
import com.app.repositories.TicketTypeRepository;

import jakarta.persistence.EntityNotFoundException;
import jakarta.transaction.Transactional;

@Service
public class BookingService {
    @Autowired
    private BookingRepository booking_repo;
    private TicketTypeRepository ticket_type_repo;
    private AttendeeRepository attendee_repo;

    @Transactional
    public BookingResponseDTO createBooking(String event_title, Long ticket_type_id, Long attendee_id) throws Exception {
        // Check if ticket type exists and that there are enough tickets left
        if (
            ticket_type_repo.findQuantityAvailableByTicketTypeId(ticket_type_id) <= 0 ||
            ticket_type_repo.findByTicketTypeId(ticket_type_id) == null
        ) {
            throw new IllegalStateException("Sorry, this ticket type is sold out.");
        }

        // Check that user hasn't booked the same ticket type before
        if (!booking_repo.existsByAttendee_AttendeeIdAndTicketType_TicketTypeId(attendee_id, ticket_type_id)) {
            throw new IllegalStateException("You have already booked this ticket type.");
        }

        // Decrement quantity_available on corresponding TicketType
        ticket_type_repo.decreaseQuantityAvailable(ticket_type_id, 1);

        // Construct Booking object to save to database
        Attendee attendee = attendee_repo.findByAttendeeId(attendee_id);
        if (attendee == null) {
            throw new EntityNotFoundException("Attendee not found.");
        }

        TicketType ticket_type = ticket_type_repo.findByTicketTypeId(ticket_type_id);
        if (ticket_type == null) {
            throw new EntityNotFoundException("Ticket type not found.");
        }


        Booking booking = new Booking();
        booking.setAttendee(attendee);
        booking.setTicketType(ticket_type);
        booking.setPaymentStatus(BookingStatus.CONFIRMED);

        Booking saved_booking = booking_repo.save(booking);

        // Generate unique booking_reference with ID generated by database
        String booking_reference = "TKT-" + Year.now().getValue() + "-" + String.format("%05d", saved_booking.getBookingId());
        saved_booking.setReference(booking_reference);

        // Re-save with reference
        booking_repo.save(saved_booking);

        // Convert to DTO and return
        return new BookingResponseDTO(saved_booking);
    }

    @Transactional
    public void cancelBooking(Long id) throws Exception {
        Booking booking = booking_repo.findByBookingId(id);
        if (booking == null) {
            throw new IllegalStateException("This booking does not exist");
        } else if (booking.getPaymentStatus() == BookingStatus.CANCELLED) {
            throw new IllegalStateException("This booking has already been cancelled.");
        }

        booking_repo.restoreTicketInventory(id);
        booking_repo.cancel(id);
    }
}
