package com.app.services;

import java.time.Year;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.app.dtos.request.BookingRequestDTO;
import com.app.dtos.response.BookingResponseDTO;
import com.app.entities.Attendee;
import com.app.entities.Booking;
import com.app.entities.TicketType;
import com.app.enums.BookingStatus;
import com.app.repositories.AttendeeRepository;
import com.app.repositories.BookingRepository;
import com.app.repositories.TicketTypeRepository;

import jakarta.persistence.EntityNotFoundException;
import jakarta.transaction.Transactional;

@Service
public class BookingService {
    @Autowired
    private BookingRepository bookingRepo;

    @Autowired
    private TicketTypeRepository ticketTypeRepo;

    @Autowired
    private AttendeeRepository attendeeRepo;

    @Transactional
    public BookingResponseDTO createBooking(BookingRequestDTO bookingReq) throws Exception {
        Long ticketTypeId = bookingReq.getTicketTypeId();
        Long attendeeId = bookingReq.getAttendeeId();

        TicketType ticketType = ticketTypeRepo.findByTicketTypeId(ticketTypeId);

        // Check if ticket type exists and that there are enough tickets left
        if (ticketType == null) {
            throw new EntityNotFoundException("Ticket type not found.");
        }

        // Check that user hasn't booked the same ticket type before
        if (ticketType.getQuantityAvailable() <= 0) {
            throw new IllegalStateException("Sorry, this ticket type is sold out.");
        }

        // Check that user hasn't booked the same ticket type before
        if (bookingRepo.existsByAttendee_AttendeeIdAndTicketType_TicketTypeId(attendeeId, ticketTypeId)) {
            throw new IllegalStateException("You have already booked this ticket type.");
        }

        // Decrement quantity_available on corresponding TicketType
        if (ticketTypeRepo.decreaseQuantityAvailable(ticketTypeId, 1) == 0) {
            throw new IllegalStateException("Sorry, this ticket type is sold out.");
        }

        // Construct Booking object to save to database
        Attendee attendee = attendeeRepo.findByAttendeeId(attendeeId);
        if (attendee == null) {
            throw new EntityNotFoundException("Attendee not found.");
        }

        Booking booking = new Booking();
        booking.setAttendee(attendee);
        booking.setTicketType(ticketType);
        booking.setPaymentStatus(BookingStatus.CONFIRMED);
        booking.setEvent(ticketType.getEvent());

        Booking savedBooking = bookingRepo.save(booking);

        // Generate unique bookingReference with ID generated by database
        String bookingReference = "TKT-" + Year.now().getValue() + "-" + String.format("%05d", savedBooking.getBookingId());
        System.out.println("REFERENCE #: " + bookingReference);
        savedBooking.setBookingReference(bookingReference);

        // Re-save with reference
        bookingRepo.save(savedBooking);

        // Convert to DTO and return
        return new BookingResponseDTO(savedBooking);
    }

    @Transactional
    public void cancelBooking(Long id) throws Exception {
        Booking booking = bookingRepo.findByBookingId(id);
        if (booking == null) {
            throw new IllegalStateException("This booking does not exist");
        } else if (booking.getPaymentStatus() == BookingStatus.CANCELLED) {
            throw new IllegalStateException("This booking has already been cancelled.");
        }

        bookingRepo.restoreTicketInventory(id);
        bookingRepo.cancel(id);
    }
}
